/**
 * Bakes the binary-ish assets into TypeScript, and must therefore run before
 * tsc.
 *
 * It bundles widget/main.ts (which imports src/layout.ts, the one copy of the
 * layout rules) and inlines it plus the Anton face into widget/index.html,
 * producing dist/widget.html: one self-contained file served as the ui://
 * resource. That HTML and the font then go into src/generated/assets.ts.
 *
 * Baking rather than shipping the files alongside the code is deliberate: the
 * deploy target is a Cloudflare Worker, and a V8 isolate has no filesystem to
 * read them back from. Anything the server needs at runtime has to be a
 * compile-time value.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { build } from "esbuild";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "dist", "widget.html");
const GENERATED = path.join(ROOT, "src", "generated", "assets.ts");

const bundle = await build({
  entryPoints: [path.join(ROOT, "widget", "main.ts")],
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "browser",
  minify: true,
  write: false,
  legalComments: "none",
});

const js = bundle.outputFiles[0].text;
const font = await readFile(path.join(ROOT, "assets", "Anton-Regular.ttf"));
const template = await readFile(path.join(ROOT, "widget", "index.html"), "utf-8");
// icon-256.png is committed output of scripts/render-icon.mjs; see assets/ICON.md.
const iconPng = await readFile(path.join(ROOT, "assets", "icon-256.png"));
const iconSvg = await readFile(path.join(ROOT, "assets", "icon.svg"));

/**
 * Substitute a placeholder that must occur exactly once.
 *
 * `String.replace` with a string pattern takes the *first* occurrence, so a
 * second mention — a token named in a comment, say — silently eats the
 * substitution and leaves the real placeholder in the output. That ships an
 * editor whose script never runs, and it fails in the host rather than here,
 * which is the expensive place to find it. So: count first, refuse otherwise.
 */
function substitute(source, token, value) {
  const occurrences = source.split(token).length - 1;
  if (occurrences !== 1) {
    throw new Error(
      `widget/index.html mentions ${token} ${occurrences} times; it must appear exactly once.`,
    );
  }
  // A literal $ in the bundle would be read as a replacement pattern.
  return source.replace(token, () => value);
}

let html = substitute(template, "__FONT__", `data:font/ttf;base64,${font.toString("base64")}`);
html = substitute(html, "__SCRIPT__", js);

for (const token of ["__FONT__", "__SCRIPT__"]) {
  if (html.includes(token)) throw new Error(`${token} survived into the built widget.`);
}

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, html);

// dist/widget.html is kept for eyeballing the built widget in a browser; the
// server reads the baked copy below.
const module = `/**
 * Generated by scripts/build-widget.mjs. Do not edit; do not commit.
 */
export const WIDGET_HTML = ${JSON.stringify(html)};

export const ANTON_TTF_BASE64 = ${JSON.stringify(font.toString("base64"))};

export const ICON_PNG_BASE64 = ${JSON.stringify(iconPng.toString("base64"))};

// Base64 for the SVG too: a data: URI carrying raw markup has to be percent-
// encoded for '#' alone, and getting that subtly wrong yields a broken icon
// rather than an error.
export const ICON_SVG_BASE64 = ${JSON.stringify(iconSvg.toString("base64"))};
`;
await mkdir(path.dirname(GENERATED), { recursive: true });
await writeFile(GENERATED, module);

console.log(
  `Wrote ${path.relative(ROOT, OUT)} (${(html.length / 1024).toFixed(0)} KB)` +
    ` and ${path.relative(ROOT, GENERATED)} (${(module.length / 1024).toFixed(0)} KB)`,
);
